theme: jekyll-theme-minimal
title: 'EvolveU Cohort3'
description: 'Competencies for the Full Stack Developer program'
logo: 'https://pbs.twimg.com/profile_images/956195352528371712/XYRz0_dl_400x400.jpg'
show_downloads: 'true'
